# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            New Zealand Oceanography Network
tagline:          'Welcome to the New Zealand Oceanographic Community Hub.'
description:      'Your go-to platform for the latest news, research developments, upcoming conferences, and resources in the field of oceanography. Join our community and help shape the future of oceanography in Aotearoa.'
url:              https://calypso-science.github.io/ponz.github.io/
baseurl:          /

author:
  name:           'Remy Zyngfogel'
  url:            https://www.calypso.science/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/calypso-science/ponz.github.io


plugins: [jekyll-paginate]